VOC 페이지 구현
DKUcouncilhomepage/student-council-homepage-frontend pull request #213
Opened 2023-04-03 16:00 UTC by sseungki98

에디터에서 입력한 글이 태그까지 포함되어 출력되는 문제는 해결 못했고, 페이지네이션이랑 검색기능이 잘 작동하는지는 잘 모르겠네요 ...ㅎㅎ

2023-04-04 12:24 UTC, ho991217 requested changes
추가하신 모든 페이지에서 `<SideNav />` 컴포넌트와 충돌이 생겨서 화면이 정상적으로 표시되지 않는 버그가 존재합니다.

2023-04-04 12:24 UTC, ho991217 commented on src/Router.tsx
> +import QnaDetail from 'pages/voc/qna/QnaDetail';
파일명은 `QnADetail.tsx`인데 `QnaDetail.tsx`로 `import`되어서 오류가 발생하네요

2023-04-05 02:16 UTC, sseungki98 commented
> 추가하신 모든 페이지에서 `<SideNav />` 컴포넌트와 충돌이 생겨서 화면이 정상적으로 표시되지 않는 버그가 존재합니다.

확인해보겠습니다

2023-04-05 04:42 UTC, sseungki98 commented on src/Router.tsx
> +import QnaDetail from 'pages/voc/qna/QnaDetail';
아 파일명 수정하고 임포트 부분을 깜빡했네요 ......ㅎㅎ

2023-04-05 04:54 UTC, sseungki98 commented on src/Router.tsx
> +import QnaDetail from 'pages/voc/qna/QnaDetail';
수정했는데 잘 뜨는지 확인해주세요 !

2023-04-07 06:55 UTC, ho991217 commented
<img width="652" alt="스크린샷 2023-04-07 15 54 49" src="https://user-images.githubusercontent.com/84632077/230557953-421aec41-89b4-4ea6-a466-daa955d8fc2a.png">
계속 `id`값이 `undefined`라고 뜨네요

2023-04-09 05:46 UTC, sseungki98 commented
> <img alt="스크린샷 2023-04-07 15 54 49" width="652" src="https://user-images.githubusercontent.com/84632077/230557953-421aec41-89b4-4ea6-a466-daa955d8fc2a.png">
> 
> 계속 `id`값이 `undefined`라고 뜨네요

SideNav를 푸쉬 안했네요 ...

2023-04-10 04:00 UTC, ho991217 approved these changes

2023-04-10 04:06 UTC, ho991217 approved these changes

2023-04-10 04:06 UTC, ho991217 approved these changes

2023-04-10 04:07 UTC, merged