feat/200 게시글 태그 기능
DKUcouncilhomepage/student-council-homepage-frontend pull request #253
Opened 2023-04-11 02:50 UTC by gaeunnlee

- 게시글 등록시 태그를 할당할 수 있도록 함
- 게시글 단건 조회시 태그 목록을 불러올 수 있도록 함

2023-04-11 03:41 UTC, ho991217 requested changes

2023-04-11 03:41 UTC, ho991217 commented on src/pages/communication/suggestion/SuggestionEditor.tsx
> +    }
403 오류가 뜨네요,
그리고 에러 모달이 작동하지 않는 듯 합니다.

2023-04-11 19:28 UTC, gaeunnlee commented on src/pages/communication/suggestion/SuggestionEditor.tsx
> +    }
관리자 계정으로만 태그가 등록되는 걸 알지 못했습니다
일반 사용자들이 태그 선택만 가능하도록 다시 구현하였습니다!
![image](https://user-images.githubusercontent.com/88781949/231268640-e3126c60-d754-457b-81b6-77a772701357.png)

2023-04-12 04:56 UTC, ho991217 approved these changes

2023-04-12 04:57 UTC, merged

2023-04-12 04:57 UTC, ho991217 approved these changes