Feat/271 본문 줄바꿈, 줄간격 수정
DKUcouncilhomepage/student-council-homepage-frontend pull request #287
Opened 2023-05-05 15:26 UTC by gaeunnlee

## What is this PR?
- 줄바꿈, 줄간격을 수정했습니다.

## What has changed?
- \r\n 대신 <br> 태그를 추가하였고, 본문의 line-height를 수정하였습니다.

## A notice to reviewers...
- 본문에 줄바꿈이 잘 되는지 확인 부탁드립니다.

2023-05-08 01:30 UTC, developerChans commented
현재 적용된 것 외에 voc, 총학소식 정돈 추가로 적용해야할 것 같습니다.

2023-05-08 01:30 UTC, developerChans requested changes
현재 적용된 것 외에 voc, 총학소식 정돈 추가로 적용해야할 것 같습니다.

2023-05-08 01:32 UTC, developerChans commented
close #271

2023-05-08 04:52 UTC, gaeunnlee commented
총학소식, q&a 줄바꿈 적용했습니다. 확인 부탁드려요.

2023-05-10 05:27 UTC, developerChans approved these changes

2023-05-10 05:27 UTC, merged